blog/urls.py
from django.urls import path
from .views import blog_page

app_name = 'blog'

urlpatterns = [
    path('<int:id>/', blog_page, name="blog_page"),
]

pages/urls.py
from django.urls import path
from blog.views import home_page
from .views import about_me, contact, gallery

app_name = 'pages'

urlpatterns = [
    path('', home_page, name="home_page"),
    path('o-mnie/', about_me, name="about_me"),
    path('kontakt/', contact, name="contact"),
    path('galeria/', gallery, name="gallery"),
]

prices/urls.py
from django.urls import path
from .views import prices_page

app_name = 'prices'

urlpatterns = [
    path('', prices_page, name="prices_page"),
]

renatakrol/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('blog/', include('blog.urls')),
    path('yoga/', include('yoga.urls')),
    path('voice/', include('voice.urls')),
    path('pilates/', include('pilates.urls')),
    path('cennik/', include('prices.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

voice/urls.py
from django.urls import path
from .views import voice_page, voice_post

app_name = 'voice'

urlpatterns = [
    path('', voice_page, name="voice_page"),
    path('<int:id>/', voice_post, name="voice_post"),
]

yoga/urls.py
from django.urls import path
from .views import yoga_page, yoga_post

app_name = 'yoga'

urlpatterns = [
    path('', yoga_page, name="yoga_page"),
    path('<int:id>/', yoga_post, name="yoga_post"),
]

pages/templates/about_me.html
{% extends 'base_index.html' %}
{% load static %}

{% block title %}
    <title>O mnie</title>
{% endblock %}

{% block content %}
    {% include 'navbar.html' %}

    <h1 class="mt-10 mx-auto">O mnie</h1>
    <hr>

    <section class="section py-0">
        <div data-provide="slider" data-autoplay="true" data-slides-to-show="2" data-css-ease="linear" data-speed="12000" data-autoplay-speed="0" data-pause-on-hover="false">
            {% for c in cblog %}
                <div class="p-2">
                    <div class="rounded bg-img h-400" style="background-image: url({{ c.photo.url }});"></div>
                </div>
            {% endfor %}
            {% for c in cyoga %}
                <div class="p-2">
                    <div class="rounded bg-img h-400" style="background-image: url({{ c.photo.url }});"></div>
                </div>
            {% endfor %}
            {% for c in cvoice %}
                <div class="p-2">
                    <div class="rounded bg-img h-400" style="background-image: url({{ c.photo.url }});"></div>
                </div>
            {% endfor %}
            {% for c in cpilates %}
                <div class="p-2">
                    <div class="rounded bg-img h-400" style="background-image: url({{ c.photo.url }});"></div>
                </div>
            {% endfor %}
            {% for b in blog %}
                <div class="p-2">
                    <div class="rounded bg-img h-400" style="background-image: url({{ b.photo.url }});"></div>
                </div>
            {% endfor %}
            {% for y in yoga %}
                <div class="p-2">
                    <div class="rounded bg-img h-400" style="background-image: url({{ y.photo.url }});"></div>
                </div>
            {% endfor %}
            {% for v in voice %}
                <div class="p-2">
                    <div class="rounded bg-img h-400" style="background-image: url({{ v.photo.url }});"></div>
                </div>
            {% endfor %}
            {% for p in pilates %}
                <div class="p-2">
                    <div class="rounded bg-img h-400" style="background-image: url({{ p.photo.url }});"></div>
                </div>
            {% endfor %}
        </div>
    </section>
    <hr>
    <div class="container">
        <div class="text-center mt-10">
            <h1>Renata Król</h1>
            <p>Yoga Głos Pilates</p>
        </div>
        <div class="text-center my-8">
            <img src="{% static 'img/renata.jpg' %}">
        </div>
        <div class="row">
            <div class="col-lg-8 mx-auto">
                <p class="lead">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed scelerisque ante non quam condimentum ultrices. Mauris consectetur quis lectus vitae sagittis. Aliquam imperdiet mattis lacinia. Sed interdum felis viverra ornare commodo. Mauris id libero velit. Aliquam eget finibus turpis. Cras sed felis arcu. Quisque eget finibus nibh. Proin lacus lorem, elementum nec sem et, imperdiet tempus lacus. Vivamus convallis sagittis porttitor. Mauris ac auctor massa, vel sollicitudin dolor.

Proin non consectetur mauris, non auctor metus. Phasellus vel turpis facilisis, aliquet arcu id, commodo lacus. Sed tincidunt nibh quis quam imperdiet dictum. Sed sit amet metus nisl. Sed vehicula nibh a ligula rutrum, et dapibus ante rhoncus. Phasellus eu consequat enim, nec pulvinar mi. In nec lobortis justo, et rhoncus tortor. Proin mollis bibendum scelerisque. Praesent iaculis dolor ut porttitor ullamcorper. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque lobortis vehicula nisl vitae commodo. Cras vitae blandit dui.

Donec in lacinia velit. Aenean ut est elementum, fringilla orci fermentum, accumsan felis. Vestibulum et mattis mauris, nec pharetra diam. Suspendisse ac turpis a tellus accumsan finibus. Donec ornare rhoncus dolor, et hendrerit dolor dictum et. Phasellus id fringilla dolor. Cras rhoncus mi vitae lacinia rhoncus.

Morbi magna lectus, volutpat ac egestas a, lobortis at erat. Vivamus et velit sit amet leo accumsan efficitur. Aliquam blandit sit amet dui a posuere. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Curabitur id lacus vel nunc tincidunt malesuada sit amet eget lacus. Phasellus vitae sapien aliquam, aliquet urna non, euismod nulla. Suspendisse vitae libero aliquet, blandit nulla non, auctor nulla. Cras elementum ipsum ligula, vitae facilisis diam elementum a. Donec suscipit dui eget odio vestibulum commodo.

Morbi posuere sapien turpis, ut maximus tellus lobortis a. Aenean imperdiet dictum risus, imperdiet consequat ex placerat ac. Quisque ornare est ut vestibulum consequat. Donec id efficitur urna. Sed mattis turpis sit amet orci fringilla egestas. In iaculis tellus dolor, ut volutpat purus pharetra eu. Aliquam vel cursus erat, nec porta est. Cras ut massa fringilla, luctus dui iaculis, malesuada ligula. Mauris pretium mattis urna a finibus. Donec nulla lacus, tempor ac nibh id, consectetur gravida orci. Etiam suscipit sed orci vel consequat. Donec non nibh ultricies, hendrerit orci ut, facilisis nisi. In maximus tellus ac enim consequat, sit amet gravida ipsum rutrum.
                </p>
            </div>
        </div>
    </div>

    {% include 'footer.html' %}
{% endblock %}

pages/templates/base_index.html
{% load static %}

<!doctype html>
<html lang="pl">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="description" content="">
    <meta name="keywords" content="">

    {% block title %}
        <title>Renata Król - Yoga Głos Pilates</title>
    {% endblock %}

    <!-- Styles -->
    <link href="{% static 'assets/css/page.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

    <!-- Favicons -->
    <link rel="apple-touch-icon" href="{% static 'assets/img/apple-touch-icon.png' %}">

    <!--  Open Graph Tags -->
    <meta property="og:title" content="TheSaaS">
    <meta property="og:description" content="A responsive, professional, and multipurpose SaaS, Software, Startup and WebApp landing template powered by Bootstrap 4.">
    <meta property="og:image" content="http://thetheme.io/thesaas/assets/img/og-img.jpg">
    <meta property="og:url" content="http://thetheme.io/thesaas/">
    <meta name="twitter:card" content="summary_large_image">

    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
    {% block content %}
    {% endblock %}

    <!-- Scripts -->
    <script src="{% static 'assets/js/page.min.js' %}"></script>
    <script src="{% static 'assets/js/script.js' %}"></script>
</body>
</html>

pages/templates/contact.html
{% extends 'base_index.html' %}
{% load static %}

{% block title %}
    <title>Kontakt</title>
{% endblock %}

{% block content %}
    {% include 'navbar.html' %}

    <header class="header text-white">
      <div class="overlay opacity-75" style="background-color: #f6f0c4; background-image: linear-gradient(315deg, #f6f0c4 0%, #d99ec9 74%);"></div>
      <div class="container text-center">

        <div class="row">
          <div class="col-md-8 mx-auto py-8">

            <h1 class="display-41">Renata Król</h1>
              <h3>Zapisz się na zajęcia</h3>

          </div>
        </div>

      </div>
    </header>

    <h1 class="mx-auto mt-6">Kontakt</h1>
    <hr>
    <h3 class="mx-auto">Dane kontaktowe:</h3>
    <div class="container mb-10 text-center mt-7">
        <p class="mx-auto">Numer telefonu: 784 123 099</p>
        <p class="mx-auto">Adres e-mail: renatajustynakrol@gmail.com</p>
        <p class="mx-auto">Facebook: Renata Król</p>
        <p class="mx-auto">Instagram: renatakrol</p>
    </div>

    {% include 'footer.html' %}
{% endblock %}

pages/templates/footer.html
<!-- Footer -->
    <footer class="footer">
      <div class="container">
        <div class="row gap-y align-items-center">

          <div class="col-6 col-lg-3">
          </div>

          <div class="col-6 col-lg-3 text-right order-lg-last">
            <div class="social">
              <a class="social-facebook" href="https://www.facebook.com/thethemeio"><i class="fa fa-facebook"></i></a>
              <a class="social-instagram" href="https://www.instagram.com/thethemeio/"><i class="fa fa-instagram"></i></a>
            </div>
          </div>

          <div class="col-lg-6">
            <div class="nav nav-bold nav-uppercase nav-trim justify-content-lg-center">
              <a class="nav-link" href="{% url 'pages:about_me' %}">O mnie</a>
              <a class="nav-link" href="{% url 'pages:contact' %}">Kontakt</a>
              <a class="nav-link" href="{% url 'pages:gallery' %}">Galeria</a>
            </div>
          </div>

        </div>
      </div>
    </footer>
<!-- /.footer -->

pages/templates/gallery1.html
{% extends 'base_index.html' %}
{% load static %}

{% block title %}
    <title>Galeria</title>
{% endblock %}

{% block content %}
    {% include 'navbar.html' %}
    <div class="container">
        <h1 class="text-center mt-10">Galeria</h1>
        <hr>
         <div class="row">
            <div class="col-lg-8 mx-auto mb-8">
                <div class="gallery gallery-4-type4" data-provide="photoswipe">
                    <a class="gallery-item" href="{{ firstPhoto.photo.url }}">
                      <img src="{{ firstPhoto.photo.url }}">
                    </a>
                    <div class="gallery-item-group">
                        {% for p in photos %}
                             <a class="gallery-item" href="{{ p.photo.url }}">
                                <img src="{{ p.photo.url }}">
                             </a>
                        {% endfor %}
                    </div>
              </div>
                <p class="mt-5 text-center">Kliknij w zdjęcie, aby zobaczyć więcej zdjęć</p>
            </div>
        </div>
    </div>
    {% include 'footer.html' %}
{% endblock %}

pages/templates/gallery2.html
{% extends 'base_index.html' %}
{% load static %}

{% block title %}
    <title>Galeria</title>
{% endblock %}

{% block content %}
    {% include 'navbar.html' %}
    <div class="container">
        <h1 class="text-center mt-10">Galeria</h1>
        <hr>
        <div class="row">
            <div class="col-lg-8 mx-auto mb-8">
                <div class="gallery gallery-4-type4" data-provide="photoswipe">
                <a class="gallery-item" href="{{ firstPhoto.photo.url }}">
                  <img src="{{ firstPhoto.photo.url }}">
                </a>
                <div class="gallery-item-group">
                    {% for p in photo %}
                        <a class="gallery-item" href="{{ p.photo.url }}">
                            <img src="{{ p.photo.url }}">
                        </a>
                    {% endfor %}
                </div>

                <div class="gallery-extra-items">
                    {% for p in photos %}
                        <a class="gallery-item" href="{{ p.photo.url }}">
                            <img src="{{ p.photo.url }}">
                        </a>
                    {% endfor %}
                </div>
              </div>
                <p class="mt-5 text-center">Kliknij w zdjęcie, aby zobaczyć więcej zdjęć</p>
            </div>
        </div>
    </div>
    {% include 'footer.html' %}
{% endblock %}

pages/templates/index.html
{% extends 'base_index.html' %}
{% load static %}

{% block title %}
    <title>Strona główna</title>
{% endblock %}

{% block content %}
    {% include 'navbar.html' %}

    <!-- Header -->
    <header class="header text-white pt-12 pb-10" style="background-image: url({{ header.photo.url }});">
        <div class="container">
            <h2 class="display-4">Renata Król</h2>
            <br>
            <h2 class="display-4">Yoga Głos Pilates</h2>
        </div>
    </header>
    <!-- /.header -->

    <!-- Main Content -->
    <main class="main-content">
      <section class="section">
        <div class="container">
          <header class="section-header">
            <small>Wpisy</small>
            <h2>Aktualności</h2>
            <hr>
          </header>

          <div class="row gap-y align-items-center">

              {% for post in posts %}
                    <div class="row gap-y align-items-center mt-7">
                        <div class="col-md-5 mx-auto">
                            <img class="rounded" src="{{ post.photo.url }}">
                        </div>
                        <div class="col-md-6 text-center text-md-left">
                            <h3>{{ post.title }}</h3>
                            <p>{{ post.description }}</p>
                            <br>
                            <a class="btn btn-outline-danger" href="{% url 'blog:blog_page' post.id %}">Czytaj dalej <i class="ti-arrow-right fs-9 ml-2"></i></a>
                        </div>
                    </div>
              {% endfor %}

          </div>
        </div>
      </section>

    </main>

    {% include 'footer.html' %}

{% endblock %}

pages/templates/navbar.html
<!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark navbar-stick-dark" data-navbar="sticky">
      <div class="container">

        <div class="navbar-left">
          <button class="navbar-toggler" type="button">&#9776;</button>
          <a class="navbar-brand" href="{% url 'pages:home_page' %}">
            <h1>RenataKrol.pl</h1>
          </a>
        </div>

        <section class="navbar-mobile">
          <span class="navbar-divider d-mobile-none"></span>

          <nav class="nav nav-navbar">
            <a class="nav-link" href="{% url 'pages:home_page' %}">Strona główna</a>
            <a class="nav-link" href="{% url 'yoga:yoga_page' %}">Yoga</a>
            <a class="nav-link" href="{% url 'voice:voice_page' %}">Głos</a>
            <a class="nav-link" href="{% url 'pilates:pilates_page' %}">Pilates</a>
            <a class="nav-link" href="{% url 'pages:about_me' %}">O mnie</a>
            <a class="nav-link" href="{% url 'pages:contact' %}">Kontakt</a>
            <a class="nav-link" href="{% url 'pages:gallery' %}">Galeria</a>
          </nav>
        </section>

        <a class="btn btn-sm btn-round btn-danger" href="{% url 'prices:prices_page' %}">Cennik</a>

      </div>
    </nav>
<!-- /.navbar -->