blog/urls.py
from django.urls import path
from .views import blog_page

app_name = 'blog'

urlpatterns = [
    path('<int:id>/', blog_page, name="blog_page"),
]

renatakrol/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('blog/', include('blog.urls')),
    path('yoga/', include('yoga.urls')),
    path('voice/', include('voice.urls')),
    path('pilates/', include('pilates.urls')),
    path('cennik/', include('prices.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

voice/urls.py
from django.urls import path
from .views import voice_page, voice_post

app_name = 'voice'

urlpatterns = [
    path('', voice_page, name="voice_page"),
    path('<int:id>/', voice_post, name="voice_post"),
]

voice/models.py
from django.db import models
from django.utils import timezone


class VoicePost(models.Model):
    title = models.CharField(max_length=128, blank=False)
    description = models.TextField(default="", blank=False)
    photo = models.ImageField(upload_to='voice_photos', blank=True, null=True)
    text = models.TextField(default="", blank=False)
    created_at = models.DateField(editable=False, default=timezone.now)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.id:
            self.created_at = timezone.now()

        return super(VoicePost, self).save(*args, **kwargs)


class VoicePhoto(models.Model):
    post = models.ForeignKey(VoicePost, on_delete=models.CASCADE, blank=True, null=True)
    photo = models.ImageField(upload_to='voice_photos', blank=True, null=True)
    isHeader = models.BooleanField()

    def __str__(self):
        if self.isHeader:
            return "Header"
        else:
            return "Voice photo " + str(self.id)

    def save(self, *args, **kwargs):
        if self.isHeader:
            try:
                tmp = VoicePhoto.objects.get(isHeader=True)
                tmp.isHeader = False
                tmp.save()
            except VoicePhoto.DoesNotExist:
                pass

        return super(VoicePhoto, self).save(*args, **kwargs)

voice/views.py
from django.shortcuts import render
from .models import VoicePost, VoicePhoto


def voice_page(request):
    posts = VoicePost.objects.all()
    header = VoicePhoto.objects.get(isHeader=True)

    return render(request, 'voice_page.html', {'posts': posts, 'header': header})


def voice_post(request, id):
    post = VoicePost.objects.get(pk=id)
    images = VoicePhoto.objects.filter(post=post)

    n = len(images)

    if n <= 3:
        return render(request, 'voice_post.html', {'post': post, 'photos': images})
    else:
        photos = []

        for i in images:
            photos.append(i)

        photo = []

        photo.append(photos[0])
        photo.append(photos[1])
        photo.append(photos[2])

        x = 3
        y = len(photos)

        while x < y:
            photos[x - 3] = photos[x]
            x += 1

        return render(request, 'voice_post2.html', {'post': post, 'photo': photo, 'photos': photos})

voice/templates/voice_page.html
{% extends 'base_index.html' %}
{% load static %}

{% block title %}
    <title>Głos</title>
{% endblock %}

{% block content %}
    {% include 'navbar.html' %}

    <!-- Header -->
    <header class="header text-white pt-12 pb-10" style="background-image: url({{ header.photo.url }});">
        <div class="container">
            <h2 class="display-4">Renata Król</h2>
            <br>
            <h2 class="display-4">Głos</h2>
        </div>
    </header>
    <!-- /.header -->

    <main class="main-content">
          <section class="section">
            <div class="container">
              <header class="section-header">
                <small>Wpisy</small>
                <h2>Głos</h2>
                <hr>
              </header>
              <div class="row gap-y align-items-center">
                  {% for post in posts %}
                        <div class="row gap-y align-items-center mt-7">
                            <div class="col-md-5 mx-auto">
                                <img class="rounded" src="{{ post.photo.url }}">
                            </div>
                            <div class="col-md-6 text-center text-md-left">
                                <h3>{{ post.title }}</h3>
                                <p>{{ post.description }}</p>
                                <br>
                                <a class="btn btn-outline-info" href="{% url 'voice:voice_post' post.id %}">Czytaj dalej <i class="ti-arrow-right fs-9 ml-2"></i></a>
                            </div>
                        </div>
                  {% endfor %}
              </div>
            </div>
          </section>

    </main>

    {% include 'footer.html' %}
{% endblock %}

voice/templates/voice_post.html
{% extends 'base_index.html' %}
{% load static %}

{% block title %}
    <title>{{ post.title }}</title>
{% endblock %}

{% block content %}
    {% include 'navbar.html' %}

        <div class="container">
            <div class="text-center mt-10">
                <h1>{{ post.title }}</h1>
                <p>{{ post.created_at }}</p>
            </div>
            <div class="text-center my-8">
                <img src="{{ post.photo.url }}">
            </div>
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <p class="lead">
                        {{ post.text }}
                    </p>
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <div class="gallery gallery-4-type4" data-provide="photoswipe">
                        <a class="gallery-item" href="{{ post.photo.url }}">
                          <img src="{{ post.photo.url }}">
                        </a>
                        <div class="gallery-item-group">
                            {% for p in photos %}
                                 <a class="gallery-item" href="{{ p.photo.url }}">
                                    <img src="{{ p.photo.url }}">
                                 </a>
                            {% endfor %}
                        </div>
                  </div>
                </div>
            </div>
        </div>

    {% include 'footer.html' %}
{% endblock %}

voice/templates/voice_post2.html
{% extends 'base_index.html' %}
{% load static %}

{% block title %}
    <title>{{ post.title }}</title>
{% endblock %}

{% block content %}
    {% include 'navbar.html' %}

    <div class="container">
        <div class="text-center mt-10">
            <h1>{{ post.title }}</h1>
            <p>{{ post.created_at }}</p>
        </div>
        <div class="text-center my-8">
            <img src="{{ post.photo.url }}">
        </div>
        <div class="row">
            <div class="col-lg-8 mx-auto">
                <p class="lead">
                    {{ post.text }}
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-8 mx-auto">
                <div class="gallery gallery-4-type4" data-provide="photoswipe">
                    <a class="gallery-item" href="{{ post.photo.url }}">
                      <img src="{{ post.photo.url }}">
                    </a>
                    <div class="gallery-item-group">
                        {% for p in photo %}
                            <a class="gallery-item" href="{{ p.photo.url }}">
                                <img src="{{ p.photo.url }}">
                            </a>
                        {% endfor %}
                    </div>

                    <div class="gallery-extra-items">
                        {% for p in photos %}
                            <a class="gallery-item" href="{{ p.photo.url }}">
                                <img src="{{ p.photo.url }}">
                            </a>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% include 'footer.html' %}
{% endblock %}